/**
 * @file
 * Spotify Lookup Module file
 */

<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function Spotify_lookup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.Spotify_lookup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<h2>' . t('Testing to see if this works') . '</h2>';


      return $output;
    default:
  }
}
