/**
 * @file
 * Hello World module file.
 */

<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function music_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.music_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<h2>' . t('Follow these steps to search for your music.') . '</h2>';
      $output .= '<p>' . t('1. "TO BE FILLED"') . '</p>';
      $output .= '<p>' . t('2. "TO BE FILLED"') . '</p>';
      $output .= '<p>' . t('3. "TO BE FILLED"') . '</p>';

      return $output;
    default:
  }
}